#!/usr/bin/env python3
"""Generate a Markdown inventory of canonical agent-facing assets."""

from __future__ import annotations

import argparse
import re
from typing import NamedTuple
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "agent-asset-inventory.md"
_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?(.*)\Z", re.DOTALL)
_KEY_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$")
_HEADER_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


class Asset(NamedTuple):
    name: str
    kind: str
    path: Path
    description: str


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _display_path(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    metadata: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key_match = _KEY_RE.match(line)
        if key_match:
            metadata[key_match.group(1)] = key_match.group(2).strip().strip("\"'")
    return metadata, match.group(2)


def _clean_cell(text: str) -> str:
    """Normalize generated Markdown table cell content onto one safe line."""
    return " ".join(text.replace("|", "\\|").split())


def _first_heading_or_sentence(path: Path, body: str) -> str:
    heading = _HEADER_RE.search(body)
    if heading:
        return _clean_cell(heading.group(1).strip())
    for line in body.splitlines():
        stripped = line.strip().lstrip("#").strip()
        if stripped:
            return _clean_cell(stripped.rstrip("."))
    return path.stem


def _command_assets(root: Path) -> list[Asset]:
    command_root = root / ".claude" / "commands"
    assets: list[Asset] = []
    for path in sorted(command_root.glob("*.md")):
        _metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=f"/{path.stem}",
                kind="Slash command",
                path=path,
                description=_first_heading_or_sentence(path, body),
            )
        )
    return assets


def _skill_assets(root: Path) -> list[Asset]:
    skill_root = root / ".claude" / "skills"
    assets: list[Asset] = []
    for path in sorted(skill_root.glob("*/SKILL.md")):
        metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=metadata.get("name", path.parent.name),
                kind="Skill",
                path=path,
                description=_clean_cell(metadata.get("description") or _first_heading_or_sentence(path, body)),
            )
        )
    return assets


def _agent_assets(root: Path) -> list[Asset]:
    agent_root = root / ".claude" / "agents"
    assets: list[Asset] = []
    for path in sorted(agent_root.glob("*.md")):
        metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=metadata.get("name", path.stem),
                kind="Subagent",
                path=path,
                description=_clean_cell(metadata.get("description") or _first_heading_or_sentence(path, body)),
            )
        )
    return assets


def collect_assets(root: Path = ROOT) -> list[Asset]:
    """Return the canonical Claude command, skill, and subagent inventory."""
    return [*_command_assets(root), *_skill_assets(root), *_agent_assets(root)]


def render_inventory(root: Path = ROOT) -> str:
    assets = collect_assets(root)
    sections = [
        "---",
        "type: Reference",
        "title: Agent Asset Inventory",
        "description: Generated index of canonical Claude commands, skills, and subagents mirrored to other agent hosts.",
        "resource: agent-asset-inventory.md",
        "tags: [agents, inventory, generated]",
        "timestamp: 2026-07-14T00:00:00Z",
        "okf_version: 0.1",
        "---",
        "",
        "# Agent Asset Inventory",
        "",
        "_Generated by `scripts/generate_agent_asset_inventory.py`; do not edit by hand._",
        "",
        "This inventory lists the canonical Claude-authored assets that are mirrored to Cursor and Codex by `scripts/sync_assistant_trees.py`.",
        "",
    ]
    for kind in ("Slash command", "Skill", "Subagent"):
        matching = [asset for asset in assets if asset.kind == kind]
        sections.extend(
            [
                f"## {kind}s",
                "",
                "| Name | Canonical path | Description |",
                "|------|----------------|-------------|",
            ]
        )
        for asset in matching:
            sections.append(
                f"| `{asset.name}` | `{_relative(asset.path, root)}` | {asset.description} |"
            )
        sections.append("")
    return "\n".join(sections).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/agent-asset-inventory.md")
    parser.add_argument("--check", action="store_true", help="Fail if the inventory is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Inventory file to write or check")
    args = parser.parse_args(argv)

    expected = render_inventory(ROOT)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        output_label = _display_path(args.output, ROOT)
        if actual != expected:
            print(f"OUT OF SYNC: {output_label}")
            print(f"Run `python {Path(__file__).relative_to(ROOT).as_posix()}` to regenerate it.")
            return 1
        print(f"in sync: {output_label}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {_display_path(args.output, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
